server:
  port: 4000

spring:
  application:
    name: member-authentication-consumer
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 47.242.214.81
    session:
      store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka


short:
  message:
    host: https://gyytz.market.alicloudapi.com
    path: /sms/smsSend
    method: POST
    appCode: 010ca100e97b4b2dae6e8154065143e3
    smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
    templateId: 908e94ccf08b4476ba6c876d13f084ad
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
