server:
  port: 3000

spring:
  application:
    name: redis-provider

  redis:
    host: 47.242.214.81
    port: 6379
    lettuce:
      shutdown-timeout: 6000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
