server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  ignored-services: "*"
  #在Zuul先买个其他微服务重定向是爆粗原本头信息
  sensitive-headers: "*"
  routes:
    portal:
      service-id: member-authentication-consumer
      path: /**


spring:
  application:
    name: zuul
  redis:
    host: 47.242.214.81
  session:
    store-type: redis
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
